// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wevafattotpzozkmgpwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndldmFmYXR0b3Rwem96a21ncHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDcyMzUsImV4cCI6MjA2NTQ4MzIzNX0.dKu6CdEbP5TBaZtsDIhNlyZo9U0rlg2L9EkrGiHLHss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);